[tools]
watchexec = "latest"
bun = "latest"
elixir = "latest"
erlang = "latest"
gleam = "latest"
node = "23"
usage = "latest"
helix = "latest"
rust-analyzer = "latest"
biome = "latest"
zellij = "latest"
bombardier = "latest"
dhall = "latest"
"cargo:bananen" = "latest"
"cargo:kc" = "latest"
"cargo:starship" = "latest"
"cargo:cargo-clean-all" = "latest"
zellij="latest"
lazygit = "latest"
neovim = "latest"

[settings]

[settings.npm]
bun = true
