# theme = "rose_pine_moon"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":write"
# Enter = "move_visual_line_down"

[keys.insert]
C-s = [":write","normal_mode"]
