import = ["~/.local/share/chezmoi/dot_config/alacritty/themes/rose-pine-moon.toml"]
[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[font]
normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }
size = 12

