format = """
[](#9A348E)\
$os\
$username\
[](bg:#C1E1C1 fg:#9A348E)\
$shell\
[](bg:#DA627D fg:#C1E1C1)\
$directory\
[](fg:#DA627D bg:#e7d1ff)\
$mise\
[](bg:#FCA17D fg:#e7d1ff)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$cpp\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$bun\
$erlang\
$nim\
$gleam\
$rust\
$scala\
$php\
$zig\
[ ](fg:#86BBD8 bg:#06969A)\
$docker_context\
$cmd_duration\
[](fg:#06969A bg:#33658A)\
$status\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E fg:#FFD6E0"
style_root = "bg:#9A348E fg:#FFD6E0"
format = '[$user ]($style)'
disabled = false

[shell]
# The shell module displays the current shell name
# It is disabled by default, but you can enable it if you want
disabled = false # Disabled by default
# Make it a bit like a pastel pistachio green color, like #C1E1C1.
style = "bg:#C1E1C1 fg:#9A348E"
# format = '[$shell ]($style)'
# The shell module can also display the shell symbol only, for powershell, zsh, bash, etc.
# Uncomment the line below to enable it
format = "[$indicator]($style)"
powershell_indicator = ""
pwsh_indicator = "PW\\$"
zsh_indicator = "Z\\$"

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E fg:#FFD6E0"
disabled = true      # Disabled by default

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"source" = "󰒋 "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = " "
style = "bg:#FCA17D fg:#2A4D69"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D fg:#2A4D69"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[bun]
disabled = false
symbol = "🧅 "
format = '[ $symbol ($version) ]($style)'
detect_files = [
    'bun.lock',
    'bun.lockb',
    'bunfig.toml',
    'package.json',
    "gleam.toml",
]
style = "bg:#86BBD8 fg:#FF6B6B"

[lua]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'


[php]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'


[nim]
symbol = "󰆥 "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[erlang]
symbol = " "
format = "[$symbol ($version) ]($style)"
style = "bg:#86BBD8 fg:#FF6B6B"
detect_files = ['rebar.config', 'elang.mk', "gleam.toml"]

[gleam]
symbol = " "
format = "[$symbol ($version) ]($style)"
style = "bg:#86BBD8 fg:#FF6B6B"
disabled = false


[zig]
symbol = "↯ "
style = "bg:#86BBD8 fg:#FF6B6B"
format = '[ $symbol ($version) ]($style)'

[status]
disabled = false
style = "bg:#33658A" # Like time.
# Heart symbol for success, broken heart for failure.
success_symbol = "♥ "
symbol = "💔"
format = "[$symbol]($style)"
map_symbol =true


[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

[cmd_duration]
format = '[ ⏱️  $duration ]($style)'
style = "bg:#06969A fg:#33658A"
min_time = 500


[mise]
symbol = "🐭"
style = "bg:#e7d1ff"
format = '[ $symbol $health ]($style)'
detect_files = [ "mise.toml", "mise.local.toml", ".mise.toml", ".mise.local.toml"]
disabled = false
